### ISSUE TITLE
Issue with `@glidejs/glide` dependency

### ISSUE THREAD

**Issue by kachkaev** [kickstartDS/blocks#1]
👋 @julrich! I have noticed an issue with `@kickstartds/button` – you have added this block in https://github.com/blockprotocol/blockprotocol/pull/252

The problem is not related to your code as such, it is to do with a very recent change on GitHub:
https://github.blog/2021-09-01-improving-git-protocol-security-github/

I can’t easily fix this issue on Block Protocol side, so it’d be great if you could help!

`@kickstartds/button` depends on `@kickstartds/base`, which [comes from npm](https://www.npmjs.com/package/@kickstartds/base). In turn, this package depends on [`@glidejs/glide`](https://www.npmjs.com/package/@types/glidejs__glide) like [this](https://unpkg.com/browse/@kickstartds/base@1.5.1/package.json):

```json

"dependencies": {
  "...": "...",
  "@glidejs/glide": "git://github.com/glidejs/glide.git#master",
  "...": "..."
```

Because of `git://` in the URL, running `yarn install` for the block fails with the following message:

```
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/glidejs/glide.git
Output:
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

Could you please relase a new version of `@kickstartds/base` by swapping `"git://github.com/glidejs/glide.git#master"` with `https://github.com/glidejs/glide.git#master"` (if you still can’t use NPM)? We’ll also need to update `package.json` and `yarn.lock` in this repo. Don’t worry about changing the block commit hash as the final step – I can do this in https://github.com/blockprotocol/blockprotocol/pull/252.

If you are currently busy, could you please leave a quick comment and I’ll think of plan B for blockprotocol.org? In theory, we can add some SSH key to our CI, but that’s somewhat undesirable. Thanks!

**Comment by julrich** [comment]
Hey @kachkaev! Thanks for the detailed explanation! 🙌

Pretty sure we can just fix this tomorrow! Just have to check if us fixing this to git was due to the latest two, so far unreleased, commits on the `master` of `glidejs/glide`. Would be surprised if that was the case though... will change as described by you, otherwise! We have a normal version requirement in that `package.json`, not sure why the .git variant is written to the lock file... will investigate, and report back 🕵️

**Comment by kachkaev** [comment]
Thanks @julrich! Looking at https://unpkg.com/browse/@kickstartds/base@1.5.1/package.json, `git://github.com/glidejs/glide.git#master` is in `package.json` too. Maybe this has already been fixed in your repo since the last release (1.5.1).

**Comment by julrich** [comment]
Yeah, that's the main thing. I just was conservative when creating the button, going with our current stable release. We're currently building up to a bigger release in ~may, so we have quite a bit on a `next` branch with beta releases... but should be stable enough to just switch to that!
https://www.npmjs.com/package/@kickstartds/base/v/1.6.0-next.10

![SmartSelect_20220316-225554_GitHub.jpg](https://user-images.githubusercontent.com/136760/158697923-3238e8f7-d7b7-48df-843b-4fcde99913ab.jpg)

**Comment by julrich** [comment]
Hey @kachkaev, updated the dependency in: https://github.com/kickstartDS/blocks/commit/aedad2f9cf7d9d03997e76239c866113af5e7b6b

Should work now, I think? Let me know if we should change anything else. Haven't touched the block commit hash, yet (as you've offered to just change it)

**Comment by kachkaev** [comment]
Thanks @julrich! I updated block hash in https://github.com/blockprotocol/blockprotocol/pull/270 and `yarn install` worked! There is a new issue with the block’s `yarn build` though:

```
/tmp/tmp-644-mU4p2EmITNu3/codeload.github.comkickstartDSblockstar.gzaedad2f9cf7d9d03997e76239c866113af5e7b6b/node_modules/@types/react/index.d.ts (3090,14): Duplicate identifier 'LibraryManagedAttributes'.
/tmp/tmp-644-mU4p2EmITNu3/codeload.github.comkickstartDSblockstar.gzaedad2f9cf7d9d03997e76239c866113af5e7b6b/node_modules/mock-block-dock/node_modules/@types/react/index.d.ts (3088,14): Duplicate identifier 'LibraryManagedAttributes'.
(node:929) UnhandledPromiseRejectionWarning: Error: No output definition. Probably caused by errors prior to this?
    at /tmp/tmp-644-mU4p2EmITNu3/codeload.github.comkickstartDSblockstar.gzaedad2f9cf7d9d03997e76239c866113af5e7b6b/node_modules/typescript-json-schema/dist/typescript-json-schema.js:1297:23
    at step (/tmp/tmp-644-mU4p2EmITNu3/codeload.github.comkickstartDSblockstar.gzaedad2f9cf7d9d03997e76239c866113af5e7b6b/node_modules/typescript-json-schema/dist/typescript-json-schema.js:44:23)
    at Object.next (/tmp/tmp-644-mU4p2EmITNu3/codeload.github.comkickstartDSblockstar.gzaedad2f9cf7d9d03997e76239c866113af5e7b6b/node_modules/typescript-json-schema/dist/typescript-json-schema.js:25:53)
    at /tmp/tmp-644-mU4p2EmITNu3/codeload.github.comkickstartDSblockstar.gzaedad2f9cf7d9d03997e76239c866113af5e7b6b/node_modules/typescript-json-schema/dist/typescript-json-schema.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/tmp/tmp-644-mU4p2EmITNu3/codeload.github.comkickstartDSblockstar.gzaedad2f9cf7d9d03997e76239c866113af5e7b6b/node_modules/typescript-json-schema/dist/typescript-json-schema.js:15:12)
    at exec (/tmp/tmp-644-mU4p2EmITNu3/codeload.github.comkickstartDSblockstar.gzaedad2f9cf7d9d03997e76239c866113af5e7b6b/node_modules/typescript-json-schema/dist/typescript-json-schema.js:1275:12)
    at Object.run (/tmp/tmp-644-mU4p2EmITNu3/codeload.github.comkickstartDSblockstar.gzaedad2f9cf7d9d03997e76239c866113af5e7b6b/node_modules/typescript-json-schema/dist/typescript-json-schema-cli.js:55:39)
    at Object.<anonymous> (/tmp/tmp-644-mU4p2EmITNu3/codeload.github.comkickstartDSblockstar.gzaedad2f9cf7d9d03997e76239c866113af5e7b6b/node_modules/typescript-json-schema/bin/typescript-json-schema:3:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
```

It might be to do with some incompatibilities between dependencies, let me check.

**Comment by julrich** [comment]
Huh, should've tested that myself before committing :O
Not really sure about that error, though: `Duplicate identifier 'LibraryManagedAttributes'.`
Sounds like some types for React maybe get loaded twice? :thinking:

**Comment by kachkaev** [comment]
Yep! That was it. Fixed in https://github.com/kickstartDS/blocks/pull/2 🙂

I temporarily switched to my fork in https://github.com/blockprotocol/blockprotocol/pull/270 and the deployment worked! 🕺

**Comment by julrich** [comment]
Ha, auto-closed the issue, too. But I'm optimistic :)

**Comment by kachkaev** [comment]
Yep, all good in https://github.com/blockprotocol/blockprotocol/pull/270 🎉

You can consider using [`yarn-deduplicate`](https://www.npmjs.com/package/yarn-deduplicate) to avoid duplicate dependencies in the future. We have this tool in [blockprotocol/blockprotocol](blockprotocol/blockprotocolhttps://github.com/blockprotocol/blockprotocol) and [hashintel/hash](https://github.com/hashintel/hash). Yarn Berry (2+) has [`dedupe` command](https://yarnpkg.com/cli/dedupe) built-in, so `yarn-deduplicate` is not needed.

**Comment by julrich** [comment]
I think we're considering upgrading yarn for our breaking release anyway, good hint! :pray:
